# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fetargo/Kursach/Modules/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(434, 628)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.btnOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout.addWidget(self.btnOpen)
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout.addWidget(self.btnBack)
        self.btnSec = QtWidgets.QPushButton(self.centralwidget)
        self.btnSec.setObjectName("btnSec")
        self.horizontalLayout.addWidget(self.btnSec)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 434, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuUserName = QtWidgets.QMenu(self.menuBar)
        self.menuUserName.setEnabled(True)
        self.menuUserName.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menuUserName.setObjectName("menuUserName")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionAccess = QtWidgets.QAction(MainWindow)
        self.actionAccess.setObjectName("actionAccess")
        self.actionLogOut = QtWidgets.QAction(MainWindow)
        self.actionLogOut.setObjectName("actionLogOut")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionCreate)
        self.menuFile.addAction(self.actionDelete)
        self.menuUserName.addAction(self.actionLogOut)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuUserName.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "File Browser"))
        self.btnBrowse.setText(_translate("MainWindow", "Home"))
        self.btnOpen.setText(_translate("MainWindow", "Open"))
        self.btnBack.setText(_translate("MainWindow", "Back"))
        self.btnSec.setText(_translate("MainWindow", "Security"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuUserName.setTitle(_translate("MainWindow", "UserName"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionCreate.setText(_translate("MainWindow", "Create"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionAccess.setText(_translate("MainWindow", "Access"))
        self.actionLogOut.setText(_translate("MainWindow", "Log Out"))
