# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fetargo/Kursach/Modules/design_auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.resize(346, 183)
        self.centralwidget = QtWidgets.QWidget(AuthWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.inputPass = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPass.setObjectName("inputPass")
        self.gridLayout.addWidget(self.inputPass, 3, 0, 1, 1)
        self.inputLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.inputLogin.setText("")
        self.inputLogin.setObjectName("inputLogin")
        self.gridLayout.addWidget(self.inputLogin, 1, 0, 1, 1)
        self.labelPass = QtWidgets.QLabel(self.centralwidget)
        self.labelPass.setObjectName("labelPass")
        self.gridLayout.addWidget(self.labelPass, 2, 0, 1, 1)
        self.labelLogin = QtWidgets.QLabel(self.centralwidget)
        self.labelLogin.setObjectName("labelLogin")
        self.gridLayout.addWidget(self.labelLogin, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAuth = QtWidgets.QPushButton(self.centralwidget)
        self.btnAuth.setObjectName("btnAuth")
        self.horizontalLayout_2.addWidget(self.btnAuth)
        self.btnSignUp = QtWidgets.QPushButton(self.centralwidget)
        self.btnSignUp.setObjectName("btnSignUp")
        self.horizontalLayout_2.addWidget(self.btnSignUp)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        AuthWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)
        AuthWindow.setTabOrder(self.inputLogin, self.inputPass)
        AuthWindow.setTabOrder(self.inputPass, self.btnAuth)
        AuthWindow.setTabOrder(self.btnAuth, self.btnSignUp)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "Authorization"))
        self.labelPass.setText(_translate("AuthWindow", "Password"))
        self.labelLogin.setText(_translate("AuthWindow", "Login"))
        self.btnAuth.setText(_translate("AuthWindow", "Sign In"))
        self.btnSignUp.setText(_translate("AuthWindow", "Sign Up"))
